/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        "primary": "#df8eff",
        "primary-dim": "#bb00fc",
        "primary-fixed": "#d878ff",
        "primary-fixed-dim": "#d061ff",
        "primary-container": "#d878ff",
        "on-primary": "#4f006d",
        "on-primary-fixed": "#000000",
        "on-primary-fixed-variant": "#4b0068",
        "on-primary-container": "#3d0055",
        "secondary": "#00f4fe",
        "secondary-dim": "#00e5ee",
        "secondary-fixed": "#00f4fe",
        "secondary-fixed-dim": "#00e5ee",
        "secondary-container": "#00696e",
        "on-secondary": "#00575b",
        "on-secondary-fixed": "#004346",
        "on-secondary-fixed-variant": "#006266",
        "on-secondary-container": "#dffdff",
        "tertiary": "#9dfaff",
        "tertiary-dim": "#63e1e7",
        "tertiary-fixed": "#72eff5",
        "tertiary-fixed-dim": "#63e1e7",
        "tertiary-container": "#72eff5",
        "on-tertiary": "#006164",
        "on-tertiary-fixed": "#004346",
        "on-tertiary-fixed-variant": "#006266",
        "on-tertiary-container": "#00585b",
        "surface": "#0c0e10",
        "surface-dim": "#0c0e10",
        "surface-bright": "#292c2f",
        "surface-variant": "#232629",
        "surface-tint": "#df8eff",
        "surface-container-lowest": "#000000",
        "surface-container-low": "#111416",
        "surface-container": "#171a1c",
        "surface-container-high": "#1d2022",
        "surface-container-highest": "#232629",
        "background": "#0c0e10",
        "on-surface": "#eeeef0",
        "on-surface-variant": "#aaabad",
        "on-background": "#eeeef0",
        "outline": "#747578",
        "outline-variant": "#46484a",
        "inverse-surface": "#f9f9fc",
        "inverse-on-surface": "#535557",
        "inverse-primary": "#9a00d0",
        "error": "#ff716c",
        "error-dim": "#d7383b",
        "error-container": "#9f0519",
        "on-error": "#490006",
        "on-error-container": "#ffa8a3",
      },
      fontFamily: {
        headline: ['Space Grotesk', 'sans-serif'],
        body: ['Manrope', 'sans-serif'],
        label: ['Manrope', 'sans-serif'],
        sans: ['Manrope', 'system-ui', 'sans-serif'],
        mono: ['JetBrains Mono', 'Fira Code', 'monospace'],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
        full: '9999px',
      },
      boxShadow: {
        'primary': '0 0 20px rgba(223,142,255,0.3)',
        'primary-sm': '0 0 10px rgba(223,142,255,0.2)',
        'secondary': '0 0 20px rgba(0,244,254,0.3)',
        'secondary-sm': '0 0 10px rgba(0,244,254,0.2)',
        'card': '0 4px 24px rgba(0,0,0,0.7)',
        'card-hover': '0 8px 32px rgba(0,0,0,0.85)',
      },
      animation: {
        'pulse-primary': 'pulsePrimary 2s cubic-bezier(0.4,0,0.6,1) infinite',
        'shimmer': 'shimmer 1.5s infinite',
        'slide-in-right': 'slideInRight 0.2s ease-out',
        'fade-in': 'fadeIn 0.15s ease-out',
      },
      keyframes: {
        pulsePrimary: {
          '0%, 100%': { opacity: '1' },
          '50%': { opacity: '0.6', boxShadow: '0 0 16px rgba(223,142,255,0.6)' },
        },
        shimmer: {
          '0%': { backgroundPosition: '-200% 0' },
          '100%': { backgroundPosition: '200% 0' },
        },
        slideInRight: {
          from: { opacity: '0', transform: 'translateX(16px)' },
          to: { opacity: '1', transform: 'translateX(0)' },
        },
        fadeIn: {
          from: { opacity: '0', transform: 'translateY(4px)' },
          to: { opacity: '1', transform: 'translateY(0)' },
        },
      },
    },
  },
  plugins: [],
}
