-- Phase 3: additive NBA market coverage.
-- Existing enum values remain valid for backwards compatibility.

ALTER TYPE "MarketType" ADD VALUE IF NOT EXISTS 'TEAM_TOTAL';
ALTER TYPE "MarketType" ADD VALUE IF NOT EXISTS 'FIRST_HALF_MONEYLINE';
ALTER TYPE "MarketType" ADD VALUE IF NOT EXISTS 'FIRST_HALF_SPREAD';
ALTER TYPE "MarketType" ADD VALUE IF NOT EXISTS 'FIRST_HALF_TOTAL';
ALTER TYPE "MarketType" ADD VALUE IF NOT EXISTS 'FIRST_HALF_TEAM_TOTAL';
ALTER TYPE "MarketType" ADD VALUE IF NOT EXISTS 'FIRST_QUARTER_MONEYLINE';
ALTER TYPE "MarketType" ADD VALUE IF NOT EXISTS 'FIRST_QUARTER_SPREAD';
ALTER TYPE "MarketType" ADD VALUE IF NOT EXISTS 'FIRST_QUARTER_TOTAL';
ALTER TYPE "MarketType" ADD VALUE IF NOT EXISTS 'FIRST_QUARTER_TEAM_TOTAL';
ALTER TYPE "MarketType" ADD VALUE IF NOT EXISTS 'PLAYER_PROP_ALTERNATE';
ALTER TYPE "MarketType" ADD VALUE IF NOT EXISTS 'DERIVATIVE';

ALTER TYPE "PropStatType" ADD VALUE IF NOT EXISTS 'TURNOVERS';
ALTER TYPE "PropStatType" ADD VALUE IF NOT EXISTS 'STOCKS';
ALTER TYPE "PropStatType" ADD VALUE IF NOT EXISTS 'DOUBLE_DOUBLE';
ALTER TYPE "PropStatType" ADD VALUE IF NOT EXISTS 'TRIPLE_DOUBLE';
